### ISSUE TITLE
Can't clash successfully if don't have ownership on enemy token

### ISSUE THREAD

**Issue by Midaychi** [tech-ticks/foundry-pokerole#29]
Trying to clash a move involving a token you don't own applies damage to yourself but errors out about being unable to modify.

**Comment by tech-ticks** [comment]
This also happens when you select enemies before rolling for damage with the "Select Targets" tool. There's a checkbox on the dialog after clicking the "Roll Damage" or "Clash" button where you can disable applying damage as a workaround until this is fixed. It also only affects non-DM players who don't have ownership over all involved tokens.
